# Generated by Django 3.2.7 on 2021-09-06 04:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_auto_20210905_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='wallpapers.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='wallpapers.location'),
        ),
    ]
