# Generated by Django 3.2.7 on 2021-09-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0003_auto_20210906_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
    ]
