# Generated by Django 3.2.7 on 2021-09-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallpapers.city'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
