# Generated by Django 3.2.7 on 2021-09-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0011_auto_20210907_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='city',
            new_name='city_name',
        ),
    ]
