# Generated by Django 3.2.7 on 2021-09-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0012_auto_20210907_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='city_name',
            new_name='city',
        ),
    ]
