# Generated by Django 3.2.7 on 2021-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0013_auto_20210907_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default=1),
        ),
    ]
